class DetailedAction:
    def __init__(self) -> None:
        self.all_detailed_actions = {

            1: {'action': 'select_planning_card', 'args': 1, 'description': '选择规划卡: 平原（棕）'},
            2: {'action': 'select_planning_card', 'args': 2, 'description': '选择规划卡: 沼泽（黑）'},
            3: {'action': 'select_planning_card', 'args': 3, 'description': '选择规划卡: 湖泊（蓝）'},
            4: {'action': 'select_planning_card', 'args': 4, 'description': '选择规划卡: 森林（绿）'},
            5: {'action': 'select_planning_card', 'args': 5, 'description': '选择规划卡: 山脉（灰）'},
            6: {'action': 'select_planning_card', 'args': 6, 'description': '选择规划卡: 荒地（红）'},
            7: {'action': 'select_planning_card', 'args': 7, 'description': '选择规划卡: 沙漠（黄）'},

            8: {'action': 'select_faction', 'args': 1, 'description': '选择派系: 神佑者'},
            9: {'action': 'select_faction', 'args': 2, 'description': '选择派系: 猫人'},
            10: {'action': 'select_faction', 'args': 3, 'description': '选择派系: 哥布林'},
            11: {'action': 'select_faction', 'args': 4, 'description': '选择派系: 幻术师'},
            12: {'action': 'select_faction', 'args': 5, 'description': '选择派系: 发明家'},
            13: {'action': 'select_faction', 'args': 6, 'description': '选择派系: 蜥蜴人'},
            14: {'action': 'select_faction', 'args': 7, 'description': '选择派系: 鼹鼠'},
            15: {'action': 'select_faction', 'args': 8, 'description': '选择派系: 僧侣'},
            16: {'action': 'select_faction', 'args': 9, 'description': '选择派系: 航海家'},
            17: {'action': 'select_faction', 'args': 10, 'description': '选择派系: 奥马尔'},
            18: {'action': 'select_faction', 'args': 11, 'description': '选择派系: 哲学家'},
            19: {'action': 'select_faction', 'args': 12, 'description': '选择派系: 通灵师'},

            20: {'action': 'select_palace_tile', 'args': 1, 'description': '选择宫殿板块1'},
            21: {'action': 'select_palace_tile', 'args': 2, 'description': '选择宫殿板块2'},
            22: {'action': 'select_palace_tile', 'args': 3, 'description': '选择宫殿板块3'},
            23: {'action': 'select_palace_tile', 'args': 4, 'description': '选择宫殿板块4'},
            24: {'action': 'select_palace_tile', 'args': 5, 'description': '选择宫殿板块5'},
            25: {'action': 'select_palace_tile', 'args': 6, 'description': '选择宫殿板块6'},
            26: {'action': 'select_palace_tile', 'args': 7, 'description': '选择宫殿板块7'},
            27: {'action': 'select_palace_tile', 'args': 8, 'description': '选择宫殿板块8'},
            28: {'action': 'select_palace_tile', 'args': 9, 'description': '选择宫殿板块9'},
            29: {'action': 'select_palace_tile', 'args': 10, 'description': '选择宫殿板块10'},
            30: {'action': 'select_palace_tile', 'args': 11, 'description': '选择宫殿板块11'},
            31: {'action': 'select_palace_tile', 'args': 12, 'description': '选择宫殿板块12'},
            32: {'action': 'select_palace_tile', 'args': 13, 'description': '选择宫殿板块13'},
            33: {'action': 'select_palace_tile', 'args': 14, 'description': '选择宫殿板块14'},
            34: {'action': 'select_palace_tile', 'args': 15, 'description': '选择宫殿板块15'},
            35: {'action': 'select_palace_tile', 'args': 16, 'description': '选择宫殿板块16'},

            36: {'action': 'select_round_booster', 'args': 1, 'description': '选择回合助推板1'},
            37: {'action': 'select_round_booster', 'args': 2, 'description': '选择回合助推板2'},
            38: {'action': 'select_round_booster', 'args': 3, 'description': '选择回合助推板3'},
            39: {'action': 'select_round_booster', 'args': 4, 'description': '选择回合助推板4'},
            40: {'action': 'select_round_booster', 'args': 5, 'description': '选择回合助推板5'},
            41: {'action': 'select_round_booster', 'args': 6, 'description': '选择回合助推板6'},
            42: {'action': 'select_round_booster', 'args': 7, 'description': '选择回合助推板7'},
            43: {'action': 'select_round_booster', 'args': 8, 'description': '选择回合助推板8'},
            44: {'action': 'select_round_booster', 'args': 9, 'description': '选择回合助推板9'},
            45: {'action': 'select_round_booster', 'args': 10, 'description': '选择回合助推板10'},

            46: {'action': 'pass_this_round', 'args': 1, 'description': '略过回合并选择回合助推板1'},
            47: {'action': 'pass_this_round', 'args': 2, 'description': '略过回合并选择回合助推板2'},
            48: {'action': 'pass_this_round', 'args': 3, 'description': '略过回合并选择回合助推板3'},
            49: {'action': 'pass_this_round', 'args': 4, 'description': '略过回合并选择回合助推板4'},
            50: {'action': 'pass_this_round', 'args': 5, 'description': '略过回合并选择回合助推板5'},
            51: {'action': 'pass_this_round', 'args': 6, 'description': '略过回合并选择回合助推板6'},
            52: {'action': 'pass_this_round', 'args': 7, 'description': '略过回合并选择回合助推板7'},
            53: {'action': 'pass_this_round', 'args': 8, 'description': '略过回合并选择回合助推板8'},
            54: {'action': 'pass_this_round', 'args': 9, 'description': '略过回合并选择回合助推板9'},
            55: {'action': 'pass_this_round', 'args': 10, 'description': '略过回合并选择回合助推板10'},
            56: {'action': 'pass_this_round', 'args': 'final', 'description': '略过回合'},

            57: {'action': 'quick_magics', 'args': 1, 'description': '快速魔力行动: 5魔力 -> 1书'},
            58: {'action': 'quick_magics', 'args': 2, 'description': '快速魔力行动: 5魔力 -> 1米宝'},
            59: {'action': 'quick_magics', 'args': 3, 'description': '快速魔力行动: 3魔力 -> 1矿'},
            60: {'action': 'quick_magics', 'args': 4, 'description': '快速魔力行动: 1魔力 -> 1钱'},
            61: {'action': 'quick_magics', 'args': 5, 'description': '快速魔力行动: 爆魔'},
            62: {'action': 'quick_magics', 'args': 6, 'description': '快速魔力行动: 1书 -> 1钱'},
            63: {'action': 'quick_magics', 'args': 7, 'description': '快速魔力行动: 1米宝 -> 1矿'},
            64: {'action': 'quick_magics', 'args': 8, 'description': '快速魔力行动: 1矿 -> 1钱'},
            65: {'action': 'quick_magics', 'args': 'pass','description': '跳过'},

            66: {'action': 'improve_navigation_level', 'args': None,'description': '升一级航行'},

            67: {'action': 'improve_shovel_level', 'args': None,'description': '升一级铲子'},

            68: {'action': 'insert_meeple', 'args': 'bank', 		'description': '选择在银行轨插入米宝'},
            69: {'action': 'insert_meeple', 'args': 'law',			'description': '选择在法律轨插入米宝'},
            70: {'action': 'insert_meeple', 'args': 'engineering', 	'description': '选择在工程轨插入米宝'},
            71: {'action': 'insert_meeple', 'args': 'medical', 		'description': '选择在医学轨插入米宝'},
            
			72: {'action': 'select_book', 'args': ('get', 'bank'), 		    'description': '选择获取一本银行书'},
            73: {'action': 'select_book', 'args': ('get', 'law'), 			'description': '选择获取一本法律书'},
            74: {'action': 'select_book', 'args': ('get', 'engineering'),	'description': '选择获取一本工程书'},
            75: {'action': 'select_book', 'args': ('get', 'medical'),	 	'description': '选择获取一本医学书'},
            76: {'action': 'select_book', 'args': ('use', 'bank'), 		    'description': '选择花费一本银行书'},
            77: {'action': 'select_book', 'args': ('use', 'law'), 			'description': '选择花费一本法律书'},
            78: {'action': 'select_book', 'args': ('use', 'engineering'),	'description': '选择花费一本工程书'},
            79: {'action': 'select_book', 'args': ('use', 'medical'),	 	'description': '选择花费一本医学书'},
            
			80: {'action': 'select_track', 'args': 'bank', 		    'description': '选择推进银行轨'},
            81: {'action': 'select_track', 'args': 'law', 			'description': '选择推进法律轨'},
            82: {'action': 'select_track', 'args': 'engineering', 	'description': '选择推进工程轨'},
            83: {'action': 'select_track', 'args': 'medical', 		'description': '选择推进医学轨'},

            84: {'action': 'select_position', 'args': (0,0),    'description': '选择地图坐标A1'},
            85: {'action': 'select_position', 'args': (0,2),    'description': '选择地图坐标A3'},
            86: {'action': 'select_position', 'args': (0,3),    'description': '选择地图坐标A4'},
            87: {'action': 'select_position', 'args': (0,4),    'description': '选择地图坐标A5'},
            88: {'action': 'select_position', 'args': (0,5),    'description': '选择地图坐标A6'},
            89: {'action': 'select_position', 'args': (0,6),    'description': '选择地图坐标A7'},
            90: {'action': 'select_position', 'args': (0,8),    'description': '选择地图坐标A9'},
            91: {'action': 'select_position', 'args': (0,9),    'description': '选择地图坐标A10'},
            92: {'action': 'select_position', 'args': (0,10),   'description': '选择地图坐标A11'},
            93: {'action': 'select_position', 'args': (0,11),   'description': '选择地图坐标A12'},
            94: {'action': 'select_position', 'args': (1,0),    'description': '选择地图坐标B1'},
            95: {'action': 'select_position', 'args': (1,3),    'description': '选择地图坐标B4'},
            96: {'action': 'select_position', 'args': (1,4),    'description': '选择地图坐标B5'},
            97: {'action': 'select_position', 'args': (1,5),    'description': '选择地图坐标B6'},
            98: {'action': 'select_position', 'args': (1,6),    'description': '选择地图坐标B7'},
            99: {'action': 'select_position', 'args': (1,8),    'description': '选择地图坐标B9'},
            100: {'action': 'select_position', 'args': (1,9),   'description': '选择地图坐标B10'},
            101: {'action': 'select_position', 'args': (1,10),  'description': '选择地图坐标B11'},
            102: {'action': 'select_position', 'args': (1,12),  'description': '选择地图坐标B13'},
            103: {'action': 'select_position', 'args': (2,0),   'description': '选择地图坐标C1'},
            104: {'action': 'select_position', 'args': (2,1),   'description': '选择地图坐标C2'},
            105: {'action': 'select_position', 'args': (2,2),   'description': '选择地图坐标C3'},
            106: {'action': 'select_position', 'args': (2,4),   'description': '选择地图坐标C5'},
            107: {'action': 'select_position', 'args': (2,5),   'description': '选择地图坐标C6'},
            108: {'action': 'select_position', 'args': (2,6),   'description': '选择地图坐标C7'},
            109: {'action': 'select_position', 'args': (2,9),   'description': '选择地图坐标C10'},
            110: {'action': 'select_position', 'args': (2,12),  'description': '选择地图坐标C13'},
            111: {'action': 'select_position', 'args': (3,0),   'description': '选择地图坐标D1'},
            112: {'action': 'select_position', 'args': (3,1),   'description': '选择地图坐标D2'},
            113: {'action': 'select_position', 'args': (3,2),   'description': '选择地图坐标D3'},
            114: {'action': 'select_position', 'args': (3,4),   'description': '选择地图坐标D5'},
            115: {'action': 'select_position', 'args': (3,5),   'description': '选择地图坐标D6'},
            116: {'action': 'select_position', 'args': (3,7),   'description': '选择地图坐标D8'},
            117: {'action': 'select_position', 'args': (3,10),  'description': '选择地图坐标D11'},
            118: {'action': 'select_position', 'args': (3,11),  'description': '选择地图坐标D12'},
            119: {'action': 'select_position', 'args': (3,12),  'description': '选择地图坐标D13'},
            120: {'action': 'select_position', 'args': (4,0),   'description': '选择地图坐标E1'},
            121: {'action': 'select_position', 'args': (4,1),   'description': '选择地图坐标E2'},
            122: {'action': 'select_position', 'args': (4,2),   'description': '选择地图坐标E3'},
            123: {'action': 'select_position', 'args': (4,3),   'description': '选择地图坐标E4'},
            124: {'action': 'select_position', 'args': (4,7),   'description': '选择地图坐标E8'},
            125: {'action': 'select_position', 'args': (4,8),   'description': '选择地图坐标E9'},
            126: {'action': 'select_position', 'args': (4,9),   'description': '选择地图坐标E10'},
            127: {'action': 'select_position', 'args': (4,10),  'description': '选择地图坐标E11'},
            128: {'action': 'select_position', 'args': (4,11),  'description': '选择地图坐标E12'},
            129: {'action': 'select_position', 'args': (4,12),  'description': '选择地图坐标E13'},
            130: {'action': 'select_position', 'args': (5,0),   'description': '选择地图坐标F1'},
            131: {'action': 'select_position', 'args': (5,4),   'description': '选择地图坐标F5'},
            132: {'action': 'select_position', 'args': (5,5),   'description': '选择地图坐标F6'},
            133: {'action': 'select_position', 'args': (5,7),   'description': '选择地图坐标F8'},
            134: {'action': 'select_position', 'args': (5,8),   'description': '选择地图坐标F9'},
            135: {'action': 'select_position', 'args': (5,10),  'description': '选择地图坐标F11'},
            136: {'action': 'select_position', 'args': (5,11),  'description': '选择地图坐标F12'},
            137: {'action': 'select_position', 'args': (5,12),  'description': '选择地图坐标F13'},
            138: {'action': 'select_position', 'args': (6,0),   'description': '选择地图坐标G1'},
            139: {'action': 'select_position', 'args': (6,2),   'description': '选择地图坐标G3'},
            140: {'action': 'select_position', 'args': (6,3),   'description': '选择地图坐标G4'},
            141: {'action': 'select_position', 'args': (6,5),   'description': '选择地图坐标G6'},
            142: {'action': 'select_position', 'args': (6,6),   'description': '选择地图坐标G7'},
            143: {'action': 'select_position', 'args': (7,1),   'description': '选择地图坐标H2'},
            144: {'action': 'select_position', 'args': (7,2),   'description': '选择地图坐标H3'},
            145: {'action': 'select_position', 'args': (7,4),   'description': '选择地图坐标H5'},
            146: {'action': 'select_position', 'args': (7,5),   'description': '选择地图坐标H6'},
            147: {'action': 'select_position', 'args': (7,6),   'description': '选择地图坐标H7'},
            148: {'action': 'select_position', 'args': (7,7),   'description': '选择地图坐标H8'},
            149: {'action': 'select_position', 'args': (7,8),   'description': '选择地图坐标H9'},
            150: {'action': 'select_position', 'args': (7,9),   'description': '选择地图坐标H10'},
            151: {'action': 'select_position', 'args': (7,10),  'description': '选择地图坐标H11'},
            152: {'action': 'select_position', 'args': (7,11),  'description': '选择地图坐标H12'},
            153: {'action': 'select_position', 'args': (8,0),   'description': '选择地图坐标I1'},
            154: {'action': 'select_position', 'args': (8,1),   'description': '选择地图坐标I2'},
            155: {'action': 'select_position', 'args': (8,2),   'description': '选择地图坐标I3'},
            156: {'action': 'select_position', 'args': (8,4),   'description': '选择地图坐标I5'},
            157: {'action': 'select_position', 'args': (8,5),   'description': '选择地图坐标I6'},
            158: {'action': 'select_position', 'args': (8,6),   'description': '选择地图坐标I7'},
            159: {'action': 'select_position', 'args': (8,7),   'description': '选择地图坐标I8'},
            160: {'action': 'select_position', 'args': (8,8),   'description': '选择地图坐标I9'},
            161: {'action': 'select_position', 'args': (8,9),   'description': '选择地图坐标I10'},
            162: {'action': 'select_position', 'args': (8,10),  'description': '选择地图坐标I11'},
            163: {'action': 'select_position', 'args': (8,11),  'description': '选择地图坐标I12'},
            164: {'action': 'select_position', 'args': (8,12),  'description': '选择地图坐标I13'},
            
            165: {'action': 'setup_build', 'args': ('build_setup', 1, False), 'description': '全图原生地选择建造一个自己的车间'},
            166: {'action': 'setup_build', 'args': ('build_setup', 5, False), 'description': '全图原生地选择建造一个自己的大学'},
            167: {'action': 'setup_build', 'args': ('build_setup', 6, True),  'description': '全图原生地选择建造一个中立的塔楼'},
            
            168: {'action': 'shovel_and_build', 'args': (0, 'build_normal', 1, False), 'description': '在原生地上建造一个车间'},
            169: {'action': 'shovel_and_build', 'args': (1, 'build_normal', 1, False), 'description': '将一个地块铲成原生地（如需，最大支持一铲）并建造车间'},
            170: {'action': 'shovel_and_build', 'args': (2, 'build_normal', 1, False), 'description': '将一个地块铲成原生地（如需，最大支持二铲）并建造车间'},
            171: {'action': 'shovel_and_build', 'args': (3, 'build_normal', 1, False), 'description': '将一个地块铲成原生地（如需，最大支持三铲）并建造车间'},
            172: {'action': 'shovel_and_build', 'args': (1,), 'description': '在一个可抵地块上铲一下但不建造'},
            173: {'action': 'shovel_and_build', 'args': (2,), 'description': '在一个可抵地块上铲两下但不建造'},
            174: {'action': 'shovel_and_build', 'args': (3,), 'description': '在一个可抵地块上铲三下但不建造'},

            175: {'action': 'gain_magics', 'args': 1, 'description': '选择吸取1点魔力'},
            176: {'action': 'gain_magics', 'args': 2, 'description': '选择吸取2点魔力'},
            177: {'action': 'gain_magics', 'args': 3, 'description': '选择吸取3点魔力'},
            178: {'action': 'gain_magics', 'args': 4, 'description': '选择吸取4点魔力'},
            179: {'action': 'gain_magics', 'args': 5, 'description': '选择吸取5点魔力'},
            180: {'action': 'gain_magics', 'args': 6, 'description': '选择吸取6点魔力'},
            181: {'action': 'gain_magics', 'args': 7, 'description': '选择吸取7点魔力'},
            182: {'action': 'gain_magics', 'args': 8, 'description': '选择吸取8点魔力'},
            183: {'action': 'gain_magics', 'args': 9, 'description': '选择吸取9点魔力'},
            184: {'action': 'gain_magics', 'args': 10, 'description': '选择吸取10点魔力'},
            185: {'action': 'gain_magics', 'args': 11, 'description': '选择吸取11点魔力'},
            186: {'action': 'gain_magics', 'args': 12, 'description': '选择吸取12点魔力'},
            187: {'action': 'gain_magics', 'args': 13, 'description': '选择吸取13点魔力'},
            188: {'action': 'gain_magics', 'args': 14, 'description': '选择吸取14点魔力'},
            189: {'action': 'gain_magics', 'args': 15, 'description': '选择吸取15点魔力'},
            190: {'action': 'gain_magics', 'args': 16, 'description': '选择吸取16点魔力'},
            191: {'action': 'gain_magics', 'args': 17, 'description': '选择吸取17点魔力'},
            192: {'action': 'gain_magics', 'args': 18, 'description': '选择吸取18点魔力'},
            193: {'action': 'gain_magics', 'args': 19, 'description': '选择吸取19点魔力'},
            194: {'action': 'gain_magics', 'args': 20, 'description': '选择吸取20点魔力'},
            195: {'action': 'gain_magics', 'args': 21, 'description': '选择吸取21点魔力'},
            196: {'action': 'gain_magics', 'args': 22, 'description': '选择吸取22点魔力'},
            197: {'action': 'gain_magics', 'args': 23, 'description': '选择吸取23点魔力'},
            198: {'action': 'gain_magics', 'args': 24, 'description': '选择吸取24点魔力'},
            199: {'action': 'gain_magics', 'args': 'give_up', 'description': '放弃吸取魔力'},

            200: {'action': 'select_city_tile', 'args': 1, 'description': '选择出两书城'},
            201: {'action': 'select_city_tile', 'args': 2, 'description': '选择出四轨城'},
            202: {'action': 'select_city_tile', 'args': 3, 'description': '选择出两铲城'},
            203: {'action': 'select_city_tile', 'args': 4, 'description': '选择出八转城'},
            204: {'action': 'select_city_tile', 'args': 5, 'description': '选择出三矿城'},
            205: {'action': 'select_city_tile', 'args': 6, 'description': '选择出米宝城'},
            206: {'action': 'select_city_tile', 'args': 7, 'description': '选择出六钱城'},

            207: {'action': 'select_ability_tile', 'args': 1, 'description': '选择能力板块1'},
            208: {'action': 'select_ability_tile', 'args': 2, 'description': '选择能力板块2'},
            209: {'action': 'select_ability_tile', 'args': 3, 'description': '选择能力板块3'},
            210: {'action': 'select_ability_tile', 'args': 4, 'description': '选择能力板块4'},
            211: {'action': 'select_ability_tile', 'args': 5, 'description': '选择能力板块5'},
            212: {'action': 'select_ability_tile', 'args': 6, 'description': '选择能力板块6'},
            213: {'action': 'select_ability_tile', 'args': 7, 'description': '选择能力板块7'},
            214: {'action': 'select_ability_tile', 'args': 8, 'description': '选择能力板块8'},
            215: {'action': 'select_ability_tile', 'args': 9, 'description': '选择能力板块9'},
            216: {'action': 'select_ability_tile', 'args': 10, 'description': '选择能力板块10'},
            217: {'action': 'select_ability_tile', 'args': 11, 'description': '选择能力板块11'},
            218: {'action': 'select_ability_tile', 'args': 12, 'description': '选择能力板块12'},

            219: {'action': 'upgrade_building', 'args': ((1,'neighbor'), 'upgrade', 2, False), 'description': '建筑升级（车间（需有邻居） -> 工会）'},
            220: {'action': 'upgrade_building', 'args': ((1,'alone_or_neighbor'), 'upgrade', 2, False), 'description': '建筑升级（车间（可无邻居） -> 工会）'},
            221: {'action': 'upgrade_building', 'args': ((2,None), 'upgrade', 3, False), 'description': '建筑升级（工会 -> 宫殿）'},
            222: {'action': 'upgrade_building', 'args': ((2,None), 'upgrade', 4, False), 'description': '建筑升级（工会 -> 学院）'},
            223: {'action': 'upgrade_building', 'args': ((4,None), 'upgrade', 5, False), 'description': '建筑升级（学院 -> 大学）'},

            224: {'action': 'magics_action', 'args': 1, 'description': '执行魔力行动（3魔力 -> 1桥）'},
            225: {'action': 'magics_action', 'args': 2, 'description': '执行魔力行动（3魔力 -> 1米宝）'},
            226: {'action': 'magics_action', 'args': 3, 'description': '执行魔力行动（4魔力 -> 2矿）'},
            227: {'action': 'magics_action', 'args': 4, 'description': '执行魔力行动（4魔力 -> 7块钱）'},
            228: {'action': 'magics_action', 'args': 5, 'description': '执行魔力行动（4魔力 -> 1铲）'},
            229: {'action': 'magics_action', 'args': 6, 'description': '执行魔力行动（6魔力 -> 2铲）'},

            230: {'action': 'build_workshop', 'args': 'build', 'description': '在第一即铲地上建造车间'},
            231: {'action': 'build_workshop', 'args': 'give_up', 'description': '放弃在第一即铲地上建造车间'},

            232: {'action': 'build_bridge', 'args': ((0, 2), (1, 0)),     'description': '建立连接A3与B1的桥梁'},
            233: {'action': 'build_bridge', 'args': ((0, 2), (2, 2)),     'description': '建立连接A3与C3的桥梁'},
            234: {'action': 'build_bridge', 'args': ((0, 8), (1, 6)),     'description': '建立连接A9与B7的桥梁'},
            235: {'action': 'build_bridge', 'args': ((0, 11), (1, 12)),   'description': '建立连接A12与B13的桥梁'},
            236: {'action': 'build_bridge', 'args': ((1, 3), (2, 2)),     'description': '建立连接B4与C3的桥梁'},
            237: {'action': 'build_bridge', 'args': ((1, 10), (2, 12)),   'description': '建立连接B11与C13的桥梁'},
            238: {'action': 'build_bridge', 'args': ((1, 10), (3, 10)),   'description': '建立连接B11与D11的桥梁'},
            239: {'action': 'build_bridge', 'args': ((2, 4), (3, 2)),     'description': '建立连接C5与D3的桥梁'},
            240: {'action': 'build_bridge', 'args': ((2, 6), (3, 7)),     'description': '建立连接C7与D8的桥梁'},
            241: {'action': 'build_bridge', 'args': ((2, 9), (3, 7)),     'description': '建立连接C10与D8的桥梁'},
            242: {'action': 'build_bridge', 'args': ((2, 9), (4, 9)),     'description': '建立连接C10与E10的桥梁'},
            243: {'action': 'build_bridge', 'args': ((2, 9), (3, 10)),    'description': '建立连接C10与D11的桥梁'},
            244: {'action': 'build_bridge', 'args': ((3, 4), (4, 3)),     'description': '建立连接D5与E4的桥梁'},
            245: {'action': 'build_bridge', 'args': ((3, 4), (5, 4)),     'description': '建立连接D5与F5的桥梁'},
            246: {'action': 'build_bridge', 'args': ((3, 5), (4, 7)),     'description': '建立连接D6与E8的桥梁'},
            247: {'action': 'build_bridge', 'args': ((3, 5), (5, 5)),     'description': '建立连接D6与F6的桥梁'},
            248: {'action': 'build_bridge', 'args': ((4, 2), (6, 2)),     'description': '建立连接E3与G3的桥梁'},
            249: {'action': 'build_bridge', 'args': ((4, 3), (5, 4)),     'description': '建立连接E4与F5的桥梁'},
            250: {'action': 'build_bridge', 'args': ((4, 3), (6, 3)),     'description': '建立连接E4与G4的桥梁'},
            251: {'action': 'build_bridge', 'args': ((4, 7), (5, 5)),     'description': '建立连接E8与F6的桥梁'},
            252: {'action': 'build_bridge', 'args': ((5, 0), (6, 2)),     'description': '建立连接F1与G3的桥梁'},
            253: {'action': 'build_bridge', 'args': ((5, 4), (6, 3)),     'description': '建立连接F5与G4的桥梁'},
            254: {'action': 'build_bridge', 'args': ((5, 7), (6, 6)),     'description': '建立连接F8与G7的桥梁'},
            255: {'action': 'build_bridge', 'args': ((5, 7), (7, 7)),     'description': '建立连接F8与H8的桥梁'},
            256: {'action': 'build_bridge', 'args': ((5, 8), (7, 8)),     'description': '建立连接F9与H9的桥梁'},
            257: {'action': 'build_bridge', 'args': ((5, 10), (7, 10)),   'description': '建立连接F11与H11的桥梁'},
            258: {'action': 'build_bridge', 'args': ((5, 11), (7, 11)),   'description': '建立连接F12与H12的桥梁'},
            259: {'action': 'build_bridge', 'args': ((6, 0), (7, 1)),     'description': '建立连接G1与H2的桥梁'},
            260: {'action': 'build_bridge', 'args': ((6, 0), (8, 0)),     'description': '建立连接G1与I1的桥梁'},
            261: {'action': 'build_bridge', 'args': ((6, 3), (7, 4)),     'description': '建立连接G4与H5的桥梁'},
            262: {'action': 'build_bridge', 'args': ((7, 2), (8, 4)),     'description': '建立连接H3与I5的桥梁'},

            263: {'action': 'book_action', 'args': 1, 'description': '执行书行动（1书 -> 5转魔）'},
            264: {'action': 'book_action', 'args': 2, 'description': '执行书行动（1书 -> 推2轨）'},
            265: {'action': 'book_action', 'args': 3, 'description': '执行书行动（2书 -> 6块钱）'},
            266: {'action': 'book_action', 'args': 4, 'description': '执行书行动（2书 -> 1车间升级）'},
            267: {'action': 'book_action', 'args': 5, 'description': '执行书行动（2书 -> 每工会2分）'},
            268: {'action': 'book_action', 'args': 6, 'description': '执行书行动（3书 -> 3铲）'},

            269: {'action': 'select_science_tile', 'args': 1, 'description': '开发高科（鬼使神差）'},
            270: {'action': 'select_science_tile', 'args': 2, 'description': '开发高科（贸易路线）'},
            271: {'action': 'select_science_tile', 'args': 3, 'description': '开发高科（教授）'},
            272: {'action': 'select_science_tile', 'args': 4, 'description': '开发高科（建筑学）'},
            273: {'action': 'select_science_tile', 'args': 5, 'description': '开发高科（建筑普查）'},
            274: {'action': 'select_science_tile', 'args': 6, 'description': '开发高科（学院）'},
            275: {'action': 'select_science_tile', 'args': 7, 'description': '开发高科（城市联盟）'},
            276: {'action': 'select_science_tile', 'args': 8, 'description': '开发高科（图书馆）'},
            277: {'action': 'select_science_tile', 'args': 9, 'description': '开发高科（交流）'},
            278: {'action': 'select_science_tile', 'args': 10, 'description': '开发高科（污水处理）'},
            279: {'action': 'select_science_tile', 'args': 11, 'description': '开发高科（蒸汽动力）'},
            280: {'action': 'select_science_tile', 'args': 12, 'description': '开发高科（炼钢厂）'},
            281: {'action': 'select_science_tile', 'args': 13, 'description': '开发高科（车间）'},
            282: {'action': 'select_science_tile', 'args': 14, 'description': '开发高科（工会）'},
            283: {'action': 'select_science_tile', 'args': 15, 'description': '开发高科（学校）'},
            284: {'action': 'select_science_tile', 'args': 16, 'description': '开发高科（大学）'},
            285: {'action': 'select_science_tile', 'args': 17, 'description': '开发高科（宫殿）'},
            286: {'action': 'select_science_tile', 'args': 18, 'description': '开发高科（纪念碑）'},

            287: {'action': 'additional_action_ability_tile_7',         'args': None, 'description': '每回合一次附加行动（能力板块7 -> 4转魔）'},
            288: {'action': 'additional_action_philosophers_faction',   'args': None, 'description': '每回合一次附加行动（哲学家派系 -> 1书）'},
            289: {'action': 'additional_action_psychics_faction',       'args': None, 'description': '每回合一次附加行动（通灵师派系 -> 5转魔并立即下一动）'},
            290: {'action': 'additional_action_palace_tile_1',          'args': None, 'description': '每回合一次附加行动（宫殿板块1 -> 2矿）'},
            291: {'action': 'additional_action_palace_tile_2',          'args': None, 'description': '每回合一次附加行动（宫殿板块2 -> 2铲）'},
            292: {'action': 'additional_action_palace_tile_3',          'args': None, 'description': '每回合一次附加行动（宫殿板块3 -> 将1学院降级为工会 + 3分1矿）'},
            293: {'action': 'additional_action_palace_tile_4',          'args': None, 'description': '每回合一次附加行动（宫殿板块4 -> 将1个车间升级为工会）'},
            294: {'action': 'additional_action_palace_tile_6',          'args': None, 'description': '每回合一次附加行动（宫殿板块6 -> 2轨）'},
            295: {'action': 'additional_action_palace_tile_13',         'args': None, 'description': '每回合一次附加行动（宫殿板块13 -> 3块钱 + 1书）'},
            296: {'action': 'additional_action_round_booster_3',        'args': None, 'description': '每回合一次附加行动（回合助推板3 -> 1轨）'},
            297: {'action': 'additional_action_round_booster_5',        'args': None, 'description': '每回合一次附加行动（回合助推板5 -> 1铲）'},
            298: {'action': 'additional_action_round_booster_8',        'args': None, 'description': '每回合一次附加行动（回合助推板8 -> 1桥）'},
            299: {'action': 'additional_action_science_tile_1',         'args': None, 'description': '每回合一次附加行动（高科板块（鬼使神差） -> 1铲）'},
            300: {'action': 'additional_action_science_tile_3',         'args': None, 'description': '每回合一次附加行动（高科板块（教授） -> 1米宝 + 3分）'},

            301: {'action': 'additional_action_ability_tile_6', 'args': None, 'description': '附加行动（能力板块6 -> 建造1个侧楼）'},
            302: {'action': 'additional_action_palace_tile_14', 'args': None, 'description': '附加行动（宫殿板块14 -> 跨越1河流地块建城）'},
            
            303: {'action': 'select_position', 'args': (0, 1),    'description': '跨越水域A2建立城市'},
            304: {'action': 'select_position', 'args': (0, 7),    'description': '跨越水域A8建立城市'},
            305: {'action': 'select_position', 'args': (0, 12),   'description': '跨越水域A13建立城市'},
            306: {'action': 'select_position', 'args': (1, 1),    'description': '跨越水域B2建立城市'},
            307: {'action': 'select_position', 'args': (1, 2),    'description': '跨越水域B3建立城市'},
            308: {'action': 'select_position', 'args': (1, 7),    'description': '跨越水域B8建立城市'},
            309: {'action': 'select_position', 'args': (1, 11),   'description': '跨越水域B12建立城市'},
            310: {'action': 'select_position', 'args': (2, 3),    'description': '跨越水域C4建立城市'},
            311: {'action': 'select_position', 'args': (2, 7),    'description': '跨越水域C8建立城市'},
            312: {'action': 'select_position', 'args': (2, 8),    'description': '跨越水域C9建立城市'},
            313: {'action': 'select_position', 'args': (2, 10),   'description': '跨越水域C11建立城市'},
            314: {'action': 'select_position', 'args': (2, 11),   'description': '跨越水域C12建立城市'},
            315: {'action': 'select_position', 'args': (3, 3),    'description': '跨越水域D4建立城市'},
            316: {'action': 'select_position', 'args': (3, 6),    'description': '跨越水域D7建立城市'},
            317: {'action': 'select_position', 'args': (3, 8),    'description': '跨越水域D9建立城市'},
            318: {'action': 'select_position', 'args': (3, 9),    'description': '跨越水域D10建立城市'},
            319: {'action': 'select_position', 'args': (4, 4),    'description': '跨越水域E5建立城市'},
            320: {'action': 'select_position', 'args': (4, 5),    'description': '跨越水域E6建立城市'},
            321: {'action': 'select_position', 'args': (4, 6),    'description': '跨越水域E7建立城市'},
            322: {'action': 'select_position', 'args': (5, 1),    'description': '跨越水域F2建立城市'},
            323: {'action': 'select_position', 'args': (5, 2),    'description': '跨越水域F3建立城市'},
            324: {'action': 'select_position', 'args': (5, 3),    'description': '跨越水域F4建立城市'},
            325: {'action': 'select_position', 'args': (5, 6),    'description': '跨越水域F7建立城市'},
            326: {'action': 'select_position', 'args': (5, 9),    'description': '跨越水域F10建立城市'},
            327: {'action': 'select_position', 'args': (6, 1),    'description': '跨越水域G2建立城市'},
            328: {'action': 'select_position', 'args': (6, 4),    'description': '跨越水域G5建立城市'},
            329: {'action': 'select_position', 'args': (6, 7),    'description': '跨越水域G8建立城市'},
            330: {'action': 'select_position', 'args': (6, 8),    'description': '跨越水域G9建立城市'},
            331: {'action': 'select_position', 'args': (6, 9),    'description': '跨越水域G10建立城市'},
            332: {'action': 'select_position', 'args': (6, 10),   'description': '跨越水域G11建立城市'},
            333: {'action': 'select_position', 'args': (6, 11),   'description': '跨越水域G12建立城市'},
            334: {'action': 'select_position', 'args': (6, 12),   'description': '跨越水域G13建立城市'},
            335: {'action': 'select_position', 'args': (7, 0),    'description': '跨越水域H1建立城市'},
            336: {'action': 'select_position', 'args': (7, 3),    'description': '跨越水域H4建立城市'},
            337: {'action': 'select_position', 'args': (7, 12),   'description': '跨越水域H13建立城市'},
            338: {'action': 'select_position', 'args': (8, 3),    'description': '跨越水域I4建立城市'},

            339: {'action': 'additional_action_moles_faction', 'args': (0, 'build_after_tunneling', 1, False), 'description': '附加行动（鼹鼠派系 -> 支付1矿 + 跨越一地块在原生地上建造车间 + 4分）'},
            340: {'action': 'additional_action_moles_faction', 'args': (1, 'build_after_tunneling', 1, False), 'description': '附加行动（鼹鼠派系 -> 支付1矿 + 跨越一地块将其铲成原生地（如需，最大支持一铲）并建造车间 + 4分）'},
            341: {'action': 'additional_action_moles_faction', 'args': (2, 'build_after_tunneling', 1, False), 'description': '附加行动（鼹鼠派系 -> 支付1矿 + 跨越一地块将其铲成原生地（如需，最大支持二铲）并建造车间 + 4分）'},
            342: {'action': 'additional_action_moles_faction', 'args': (3, 'build_after_tunneling', 1, False), 'description': '附加行动（鼹鼠派系 -> 支付1矿 + 跨越一地块将其铲成原生地（如需，最大支持三铲）并建造车间 + 4分）'},
            343: {'action': 'additional_action_moles_faction', 'args': (1,), 'description': '附加行动（鼹鼠派系 -> 支付1矿 + 跨越一地块铲一下但不建造 + 4分）'},
            344: {'action': 'additional_action_moles_faction', 'args': (2,), 'description': '附加行动（鼹鼠派系 -> 支付1矿 + 跨越一地块铲两下但不建造 + 4分）'},
            345: {'action': 'additional_action_moles_faction', 'args': (3,), 'description': '附加行动（鼹鼠派系 -> 支付1矿 + 跨越一地块铲三下但不建造 + 4分）'},

            346: {'action': 'select_tunneling_or_flight_in_spade', 'args': 'normal',   'description': '附加立即行动（鼹鼠派系/宫殿板块9 -> 在常规范围内使用铲）'},
            347: {'action': 'select_tunneling_or_flight_in_spade', 'args': 'tunneling', 'description': '附加立即行动（鼹鼠派系 -> 支付1矿 + 跨越一地块使用铲 + 4分）'},
            348: {'action': 'select_tunneling_or_flight_in_spade', 'args': 'flight',    'description': '附加立即行动（宫殿板块9 -> 支付1米宝 + 跨越一或两地块使用铲 + 5分）'},

            349: {'action': 'additional_action_palace_tile_9', 'args': (0, 'build_after_flight', 1, False), 'description': '附加行动（宫殿板块9 -> 支付1米宝 + 跨越一至两地块在原生地上建造车间 + 5分）'},
            350: {'action': 'additional_action_palace_tile_9', 'args': (1, 'build_after_flight', 1, False), 'description': '附加行动（宫殿板块9 -> 支付1米宝 + 跨越一至两地块将其铲成原生地（如需，最大支持一铲）并建造车间 + 5分）'},
            351: {'action': 'additional_action_palace_tile_9', 'args': (2, 'build_after_flight', 1, False), 'description': '附加行动（宫殿板块9 -> 支付1米宝 + 跨越一至两地块将其铲成原生地（如需，最大支持二铲）并建造车间 + 5分）'},
            352: {'action': 'additional_action_palace_tile_9', 'args': (3, 'build_after_flight', 1, False), 'description': '附加行动（宫殿板块9 -> 支付1米宝 + 跨越一至两地块将其铲成原生地（如需，最大支持三铲）并建造车间 + 5分）'},
            353: {'action': 'additional_action_palace_tile_9', 'args': (1,), 'description': '附加行动（宫殿板块9 -> 支付1米宝 + 跨越一至两地块铲一下但不建造 + 5分）'},
            354: {'action': 'additional_action_palace_tile_9', 'args': (2,), 'description': '附加行动（宫殿板块9 -> 支付1米宝 + 跨越一至两地块铲两下但不建造 + 5分）'},
            355: {'action': 'additional_action_palace_tile_9', 'args': (3,), 'description': '附加行动（宫殿板块9 -> 支付1米宝 + 跨越一至两地块铲三下但不建造 + 5分）'},
        }
